export const SELECT_OPTION = 'SELECT_OPTION';
export const SHIFT_OPTIONS_LEFT = 'SHIFT_OPTIONS_LEFT';
export const SHIFT_OPTIONS_RIGHT = 'SHIFT_OPTIONS_RIGHT';

export const CHANGE_DISTANCE = 'CHANGE_DISTANCE';
export const SELECT_CONNECTION = 'SELECT_CONNECTION';